name: "Create Release"

on:
  push:
    branches:
      - main

jobs:
  create_release:
    name: "Create GitHub Release"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2

      - name: "Set up Git"
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: "Get version from file"
        id: get_version
        run: |
          VERSION=$(cat VERSION)
          echo "::set-output name=version::$VERSION"

      - name: "Create Release"
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          release_name: Release ${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: false

      - name: "Increment version"
        run: |
          current_version=$(cat VERSION)
          IFS='.' read -r -a version_parts <<< "$current_version"
          version_parts[2]=$((version_parts[2] + 1))
          new_version="${version_parts[0]}.${version_parts[1]}.${version_parts[2]}"
          echo "$new_version" > VERSION
          git add VERSION
          git commit -m "Bump version to $new_version"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
